export enum PostCommentsTypes {
    GET_POST_COMMENTS = '@@posts/GET_POST_COMMENTS',
    GET_POST_COMMENTS_SUCCESS = '@@posts/GET_POST_COMMENTS_SUCCESS',
    GET_POST_COMMENTS_FAILURE = '@@posts/GET_POST_COMMENTS_FAILURE',

    CLEAR_POST_COMMENTS = '@@posts/CLEAR_POST_COMMENTS',
}