export enum PostsTypes {
    GET_POSTS = '@@posts/GET_POSTS',
    GET_POSTS_SUCCESS = '@@posts/GET_POSTS_SUCCESS',
    GET_POSTS_FAILURE = '@@posts/GET_POSTS_FAILURE',

    SAVE_POST = '@@posts/SAVE_POST',
    SAVE_POST_SUCCESS = '@@posts/SAVE_POST_SUCCESS',
    SAVE_POST_FAILURE = '@@posts/SAVE_POST_FAILURE',

    DELETE_POST = '@@posts/DELETE_POST',
    DELETE_POST_SUCCESS = '@@posts/DELETE_POST_SUCCESS',
    DELETE_POST_FAILURE = '@@posts/DELETE_POST_FAILUREu',

    CLEAR_POSTS = '@@posts/CLEAR_POSTS',
}